- Cargo.lock
- crates/plugin_react_utils/Cargo.toml
- crates/plugin_react_utils/src/import_react.rs
- crates/plugin_react_utils/src/remove_effect.rs
- crates/plugin_react_utils/src/remove_prop_types.rs
- crates/shared/src/lib.rs
- crates/swc_plugins_core/Cargo.toml
- crates/swc_plugins_core/src/transform.rs
- crates/swc_plugins_utils/Cargo.toml
- crates/swc_plugins_utils/src/lib.rs
- package.json
Make a separate crate for swc_plugins_utils
> feat: make utils to swc_plugins_utils

- package.json
- tests/index.test.ts
> chore(release): publish')

- .npmignore
- package.json
- Remove `.node` files generated by CI
- Remove useless files in npm
> chore(release): publish

- Cargo.lock
- crates/plugin_modularize_imports/tests/fixture.rs
- crates/shared/Cargo.toml
- crates/swc_plugins_core/Cargo.toml
- crates/swc_plugins_core/src/transform.rs
- crates/swc_plugins_core/tests/main.rs
- Update swc_core version, keep the same with rspack
- Adjust some api due to swc_core version changing
> chore: update

- .github/workflows/bench.yml
- crates/swc_plugins_core/benches/main.rs
- crates/swc_plugins_core/tests/main.rs
> bench: init test benchmark

- .eslintrc.js
- binding.js
- crates/swc_plugins_core/src/minify.rs
- crates/swc_plugins_core/src/transform.rs
- crates/swc_plugins_core/tests/main.rs
- package.json
- types/index.d.ts
> chore: api change for better use

- crates/binding/src/lib.rs
- crates/swc_plugins_core/benches/main.rs
- crates/swc_plugins_core/src/minify.rs
- crates/swc_plugins_core/src/transform.rs
- crates/swc_plugins_core/src/types.rs
- crates/swc_plugins_core/tests/main.rs
- crates/test_plugins/src/lib.rs
- pnpm-lock.yaml
> refactor(binding_types, core)

- .github/workflows/ci.yml
> feat: add cargo clippy on CI

- .github/workflows/ci.yml
Reverts modern-js-dev/swc-plugins#43
> Revert "Ci/add clippy"

- .github/workflows/ci.yml
Reverts modern-js-dev/swc-plugins#42
> Revert "feat: add cargo clippy on CI"

- .github/workflows/ci.yml
Add cargo-clippy and cargo-fmt on CI
> feat(CI): add cargo-clippy and cargo fmt

- .github/workflows/ci.yml
Fix downloaded artifacts path, so it can be used for testing
> fix(CI): download artifact to current working directory

- .github/workflows/ci.yml
- package.json
Reverts modern-js-dev/swc-plugins#52
> Revert "feat: test ci"

- .vscode/settings.json
- Cargo.lock
- crates/binding/src/binding_types/extensions.rs
- crates/plugin_modernjs_ssr_loader_id/Cargo.toml
- crates/plugin_modernjs_ssr_loader_id/src/lib.rs
- crates/shared/src/lib.rs
- crates/swc_plugins_core/Cargo.toml
- crates/swc_plugins_core/src/pass.rs
- crates/swc_plugins_core/src/transform.rs
- crates/swc_plugins_core/src/types.rs
- crates/test_plugins/src/lib.rs
Add `plugin_modernjs_ssr_loader_id` for `modern.js`
> feat: add plugin_modernjs_ssr_loader_id

- Cargo.lock
- crates/swc_plugins_core/Cargo.toml
- crates/swc_plugins_core/src/minify.rs
- crates/swc_plugins_core/src/transform.rs
> feat: add ctrl c handler

- .changeset/config.json
- .changeset/long-spiders-whisper.md
- .github/workflows/ci.yml
- package.json
- pnpm-lock.yaml
> feat: changeset

- crates/plugin_modernjs_ssr_loader_id/src/lib.rs
> fix: fix type error

- .changeset/smart-beans-care.md
- .github/workflows/publish-crate.yml
Support publish plugin_import on CI
> feat(CI): add publish plugin-import crate on CI

- .changeset/dirty-rockets-attack.md
- readme.md
> fix: README typo

- .changeset/empty-mice-poke.md
- .github/workflows/ci.yml
- .github/workflows/publish-crate.yml
- .vscode/settings.json
- Cargo.lock
- binding.js
- crates/binding/Cargo.toml
- crates/binding/src/lib.rs
- crates/swc_plugins_core/src/lib.rs
- crates/swc_plugins_core/src/minify.rs
- index.js
- types/index.d.ts
- support minify css
- change command to publish crate
> feat: support minify css

- crates/plugin_import/Cargo.toml
> chore(plugin-import): add license and description

- .changeset/famous-ducks-jog.md
- Cargo.lock
- Cargo.toml
- crates/binding/src/binding_types/mod.rs
- crates/binding/src/binding_types/plugin_emotion.rs
- crates/binding/src/binding_types/plugin_import.rs
- crates/binding/src/binding_types/plugin_styled_components.rs
- crates/binding/src/thread_safe_function.rs
- crates/plugin_import/Cargo.toml
- crates/plugin_import/src/lib.rs
- crates/plugin_lodash/src/lib.rs
- crates/plugin_lodash/src/mappings.rs
- crates/swc_plugins_core/src/minify.rs
- crates/swc_plugins_core/src/transform.rs
- crates/test_plugins/src/fixture.rs
- crates/test_plugins/src/plugin_testing.rs
- crates/test_plugins/src/utils.rs
> chore: :arrow_up: bump swc

- .changeset/tasty-melons-hunt.md
- .github/workflows/release-pull-request.yml
- .github/workflows/release.yml
- package.json
Refactor CI, run multi-platform compilation only when we are ready to release.
- run rust side test using linux instead of all platforms in normal PR
- when we are ready to release, run multi-platform build
> refactor: :art: refactor release CI

- .changeset/ten-beds-compare.md
- package.json
Add @swc/helpers as peer dependencies
> chore: add peer dependencies

- .changeset/lucky-rabbits-hang.md
- Cargo.lock
- Cargo.toml
- crates/plugin_import/Cargo.toml
- crates/plugin_lodash/Cargo.toml
- crates/plugin_lodash/src/mappings.rs
- crates/swc_plugins_collection/Cargo.toml
> chore: bump swc_core

- .changeset/clever-pigs-draw.md
- Cargo.lock
- Cargo.toml
- package.json
> chore: update dependencies

- .changeset/clever-ways-compete.md
- Cargo.lock
- Cargo.toml
- crates/plugin_import/Cargo.toml
- crates/plugin_lodash/Cargo.toml
- crates/swc_plugins_collection/Cargo.toml
> chore: bump dependencies

- .changeset/eighty-pumpkins-reply.md
- Cargo.lock
- Cargo.toml
> chore: upgrade swc_core

- .changeset/thirty-rockets-eat.md
- Cargo.lock
- crates/plugin_loadable_components/Cargo.toml
- crates/plugin_loadable_components/src/lib.rs
- crates/plugin_loadable_components/src/util.rs
Enable wasm feature, and upgrade swc_core patch version
> feat: enable wasm feature, upgrade swc_core

- .changeset/tough-dots-march.md
- types/swcTypes.d.ts
> fix: fix mangle options type def

- .changeset/selfish-clouds-change.md
- .github/workflows/bump-swc.yml
- Cargo.lock
- Cargo.toml
> feat: bump swc_core automatically

- .changeset/lazy-worms-yell.md
- Cargo.lock
- Cargo.toml
Bump swc_core to latest, fixed some minimization bugs
> chore: bump swc

- .changeset/blue-falcons-enjoy.md
- binding.js
Binding should not modify original config
> fix: dont modify original config

- types/swcTypes.d.ts
https://github.com/swc-project/swc/blob/a0408358301cf03f2cf1c3a33c3271b1ea29c84e/packages/types/index.ts#L794-L797
> feat: add swc transform decoratorVersion type

- .changeset/blue-kangaroos-vanish.md
- Cargo.lock
- Cargo.toml
- crates/binding/src/binding_types/plugin_modularize_imports.rs
- crates/binding/src/lib.rs
- crates/integration_tests/tests/plugin_lock_corejs_version/fixtures/lock-corejs/esm/expected.js
- crates/plugin_lodash/src/lib.rs
- crates/swc_plugins_collection/Cargo.toml
- crates/swc_plugins_core/src/minify.rs
- crates/swc_plugins_core/src/transform.rs
- packages/Cargo.toml
bump swc_core and other dependencies
> chore: bump deps

- .changeset/chilly-comics-deny.md
- Cargo.lock
- Cargo.toml
- crates/integration_tests/tests/plugin_ssr_loader_id/main.rs
- crates/plugin_import/src/lib.rs
- crates/plugin_loadable_components/src/lib.rs
- crates/plugin_lodash/src/lib.rs
- crates/plugin_react_const_elements/src/immutable.rs
- crates/plugin_react_const_elements/src/lib.rs
- crates/plugin_react_utils/src/import_react.rs
- crates/plugin_react_utils/src/remove_prop_types.rs
- crates/swc_plugins_core/benches/main.rs
- crates/swc_plugins_core/src/minify.rs
- crates/swc_plugins_core/src/transform.rs
- crates/swc_plugins_utils/src/lib.rs
- packages/Cargo.toml
- types/swcTypes.d.ts
bump swc_core to fix https://github.com/swc-project/swc/issues/9432
changs: https://swc.rs/docs/plugin/selecting-swc-core#v098x-
> feat: bump swc_core
